class GithubRepository:
    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.node_id = kwargs.get("node_id")
        self.name = kwargs.get("name")
        self.full_name = kwargs.get("full_name")
        self.private = kwargs.get("private")
        self.owner_login = kwargs.get("owner_login")
        self.owner_id = kwargs.get("owner_id")
        self.owner_node_id = kwargs.get("owner_node_id")
        self.owner_avatar_url = kwargs.get("owner_avatar_url")
        self.owner_html_url = kwargs.get("owner_html_url")
        self.html_url = kwargs.get("html_url")
        self.description = kwargs.get("description")
        self.fork = kwargs.get("fork")
        self.url = kwargs.get("url")
        self.created_at = kwargs.get("created_at")
        self.updated_at = kwargs.get("updated_at")
        self.pushed_at = kwargs.get("pushed_at")
        self.git_url = kwargs.get("git_url")
        self.ssh_url = kwargs.get("ssh_url")
        self.clone_url = kwargs.get("clone_url")
        self.svn_url = kwargs.get("svn_url")
        self.homepage = kwargs.get("homepage")
        self.size = kwargs.get("size")
        self.stargazers_count = kwargs.get("stargazers_count")
        self.watchers_count = kwargs.get("watchers_count")
        self.language = kwargs.get("language")
        self.has_issues = kwargs.get("has_issues")
        self.has_projects = kwargs.get("has_projects")
        self.has_downloads = kwargs.get("has_downloads")
        self.has_wiki = kwargs.get("has_wiki")
        self.has_pages = kwargs.get("has_pages")
        self.forks_count = kwargs.get("forks_count")
        self.open_issues_count = kwargs.get("open_issues_count")
        self.default_branch = kwargs.get("default_branch")

    def __str__(self):
        return self.full_name
