# Generated by Django 5.2.1 on 2025-07-21 16:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notestoself',
            name='table_of_contents',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
