# Generated by Django 5.2.1 on 2025-08-11 03:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_notestoself_table_of_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notestoself',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Title of the resume, e.g., 'Senior Backend Developer Resume'", max_length=255)),
                ('objective', models.CharField(help_text='Short professional summary.', max_length=500)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO & ATS', max_length=255)),
                ('prompt', models.CharField(blank=True, help_text='Prompt for AI resume generation (if applicable).', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('description', tinymce.models.HTMLField(help_text='Project details (supports rich text).')),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Additional details (supports rich text).')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='blog.resume')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('date_obtained', models.DateField()),
                ('credential_url', models.URLField(blank=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='blog.resume')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Start date.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if still employed).', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', tinymce.models.HTMLField(help_text='Responsibilities & achievements (supports rich text).')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated tech stack keywords.', max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='blog.resume')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
