# Generated by Django 5.2.1 on 2025-08-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_notestoself_author_resume_projects_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the certification.'),
        ),
    ]
