# Generated by Django 5.2.1 on 2025-10-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_clicklog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotesToSelf",
            new_name="Posts",
        ),
    ]
