# Generated by Django 5.2.1 on 2025-10-12 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20251012_1026'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='posts',
            new_name='posts_title_year_idx',
            old_name='notes_title_year_idx',
        ),
        migrations.RenameIndex(
            model_name='posts',
            new_name='posts_slug_idx',
            old_name='notes_slug_idx',
        ),
        migrations.AddField(
            model_name='posts',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content issues', null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for search engines (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='posts',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom title tag for SEO (max 70 chars)', max_length=70),
        ),
        migrations.AddField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
