# Generated by Django 5.2.7 on 2025-10-21 04:46

import apps.blog.models.abstract.webp_image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_notes_title_year_idx_posts_title_year_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=apps.blog.models.abstract.webp_image_field.WebPImageField(blank=True, null=True, upload_to='posts/thumbnails/'),
        ),
    ]
