"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import environ
from pathlib import Path

env = environ.Env()

BASE_DIR = environ.Path(__file__) - 3

environ.Env.read_env(BASE_DIR(".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-oh&5$nm+z31id6aziczld*h-o3&)&3n2u4)gv7gm=48l1vsk89"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

INTERNAL_IPS = []

# Application definition

LOCAL_APPS = [
    "apps.blog.apps.BlogConfig",
]

THIRD_PARTY_APPS = [
    "tailwind",
    "theme",
    "tinymce",
    "taggit",
    "taggit_labels",
    "active_link",
    "django_celery_results",
]

INSTALLED_APPS = (
    [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
    ]
    + THIRD_PARTY_APPS
    + LOCAL_APPS
)

MAX_UPLOAD_SIZE = 2 * 1024 * 1024  # 2 MB

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "region_name": env.str("SUPABASE_S3_REGION"),
            "access_key": env.str("SUPABASE_S3_ACCESS_KEY"),
            "secret_key": env.str("SUPABASE_S3_SECRET_ACCESS_KEY"),
            "bucket_name": env.str("SUPABASE_STORAGE_BUCKET_NAME"),
            "endpoint_url": env.str("SUPABASE_S3_ENDPOINT_URL"),
            "querystring_auth": False,  # Setting AWS_QUERYSTRING_AUTH to False to remove query parameter authentication from generated URLs. This can be useful if your S3 buckets are public.
            "custom_domain": env.str("SUPABASE_CUSTOM_DOMAIN"),
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.blog.context.global_context.shared",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "db.sqlite3",
    }
}

REDIS_URL = f"redis://:{env.str('REDIS_PASSWORD')}@{env.str('REDIS_HOST')}:{env.str('REDIS_PORT')}/{env.str('REDIS_DB_INDEX')}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Extra static directories (optional)
STATICFILES_DIRS = [
    Path(str(BASE_DIR)) / "static",  # Your project-level static folder
    Path(str(BASE_DIR)) / "theme" / "static",  # Tailwind theme app
]

STATIC_ROOT = Path(str(BASE_DIR)) / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = Path(str(BASE_DIR)) / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "blog.User"

TAILWIND_APP_NAME = "theme"


# NPM_PATH = get_npm_path()

# if not NPM_PATH:
#     raise RuntimeError("NPM is not installed or not in PATH.")
# else:
#     NPM_BIN_PATH = NPM_PATH

TINYMCE_PLUGINS = "advlist,autolink,lists,link,image,charmap,preview,anchor,searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,help,wordcount,emoticons,autoresize,codesample"

TINYMCE_TOOLBAR = (
    "undo redo | blocks fontsize | bold italic backcolor | table tabledelete | tablecellborderstyle tablecellvalign tableprops tablerowprops tablecellprops | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat help | visualblocks emoticons code preview fullscreen | image codesample link anchor hr blockquote charmap",
)

path_to_image_upload_handler = (
    Path(str(BASE_DIR)) / "static" / "js/tinymce_images_upload_handler.js"
)
tinymce_images_upload_handler = path_to_image_upload_handler.read_text(encoding="utf-8")

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "plugins": TINYMCE_PLUGINS,
    "toolbar": TINYMCE_TOOLBAR,
    "min_height": 600,
    "max_height": 1200,
    "images_upload_url": "/admin/tinymce-upload/",
    "images_upload_credentials": True,
    "images_upload_handler": tinymce_images_upload_handler,
    "images_file_types": "jpeg,jpg,png,gif,webp,svg",
    "link_default_target": "_blank",
    "codesample_languages": [
        {"text": "HTML/XML", "value": "markup"},
        {"text": "JavaScript", "value": "javascript"},
        {"text": "CSS", "value": "css"},
        # {"text": "PHP", "value": "php"},
        # {"text": "Ruby", "value": "ruby"},
        {"text": "Python", "value": "python"},
        # {"text": "Java", "value": "java"},
        # {"text": "C", "value": "c"},
        # {"text": "C#", "value": "csharp"},
        # {"text": "C++", "value": "cpp"},
        {"text": "Git", "value": "git"},
        {"text": "TypeScript", "value": "typescript"},
        {"text": "SQL", "value": "sql"},
        {"text": "JSON", "value": "json"},
        {"text": "Plain Text", "value": "plaintext"},
    ],
    "codesample_global_prismjs": True,
    "table_border_styles": [
        {"title": "Solid", "value": "solid"},
        {"title": "Dotted", "value": "dotted"},
        {"title": "Dashed", "value": "dashed"},
        {"title": "Double", "value": "double"},
        {"title": "Groove", "value": "groove"},
        {"title": "Ridge", "value": "ridge"},
        {"title": "Inset", "value": "inset"},
        {"title": "Outset", "value": "outset"},
        {"title": "None", "value": "none"},
        {"title": "Hidden", "value": "hidden"},
    ],
}

GITHUB_PERSONAL_ACCESS_TOKEN = env.str("GITHUB_PERSONAL_ACCESS_TOKEN", default="")
GITHUB_BASE_URL = env.str("GITHUB_BASE_URL", default="https://api.github.com")
GITHUB_API_VERSION = env.str("GITHUB_API_VERSION", default="2022-11-28")

CELERY_REDIS_URL = (
    f"redis://:{env.str('REDIS_PASSWORD')}@redis:{env.str('REDIS_PORT')}/"
)
CELERY_BROKER_URL = CELERY_REDIS_URL + env.str("CELERY_BROKER_REDIS_DB_INDEX")
CELERY_RESULT_BACKEND = CELERY_REDIS_URL + env.str("CELERY_BACKEND_REDIS_DB_INDEX")
